package i18n

// WatchLabels holds translatable UI text for WatchBot notifications.
// Note: Benchmark image/table labels stay in English; only message content is translated.
type WatchLabels struct {
	DigestTitle    string // email subject / header
	ChangesFound   string // "%d page changes detected" (uses fmt.Sprintf)
	NoChanges      string // "No changes detected"
	Severity       string // "Severity"
	Critical       string
	Important      string
	Minor          string
	ViewPage       string // "View Page →"
	Unchanged      string // "No changes:"
	GeneratedBy    string
	BenchmarkTitle string // "📊 AI Benchmark Update"
	BenchmarkDesc  string // description text
}

// GetWatchLabels returns the WatchBot UI labels for a given language.
func GetWatchLabels(lang Language) WatchLabels {
	labels, ok := watchLabelMap[lang]
	if !ok {
		return watchLabelMap[LangEN]
	}
	return labels
}

var watchLabelMap = map[Language]WatchLabels{
	LangZH: {
		DigestTitle:    "竞品监控报告",
		ChangesFound:   "检测到 %d 个页面发生变化",
		NoChanges:      "未发生变化",
		Severity:       "严重程度",
		Critical:       "严重",
		Important:      "重要",
		Minor:          "次要",
		ViewPage:       "查看原页面 →",
		Unchanged:      "未变化",
		GeneratedBy:    "由 WatchBot 自动生成",
		BenchmarkTitle: "📊 AI Benchmark 更新",
		BenchmarkDesc:  "以下模型在本周有新评测数据",
	},
	LangEN: {
		DigestTitle:    "Competitor Watch Report",
		ChangesFound:   "%d page changes detected",
		NoChanges:      "No changes detected",
		Severity:       "Severity",
		Critical:       "Critical",
		Important:      "Important",
		Minor:          "Minor",
		ViewPage:       "View Page →",
		Unchanged:      "Unchanged",
		GeneratedBy:    "Auto-generated by WatchBot",
		BenchmarkTitle: "📊 AI Benchmark Update",
		BenchmarkDesc:  "New benchmark data available this week",
	},
	LangJA: {
		DigestTitle:    "競合モニタリングレポート",
		ChangesFound:   "%d ページの変更を検出",
		NoChanges:      "変更なし",
		Severity:       "重要度",
		Critical:       "重大",
		Important:      "重要",
		Minor:          "軽微",
		ViewPage:       "元ページを見る →",
		Unchanged:      "変更なし",
		GeneratedBy:    "WatchBot により自動生成",
		BenchmarkTitle: "📊 AI ベンチマーク更新",
		BenchmarkDesc:  "今週の新しいベンチマークデータ",
	},
	LangKO: {
		DigestTitle:    "경쟁사 모니터링 리포트",
		ChangesFound:   "%d 페이지 변경 감지",
		NoChanges:      "변경 없음",
		Severity:       "심각도",
		Critical:       "심각",
		Important:      "중요",
		Minor:          "경미",
		ViewPage:       "원본 페이지 보기 →",
		Unchanged:      "변경 없음",
		GeneratedBy:    "WatchBot 자동 생성",
		BenchmarkTitle: "📊 AI 벤치마크 업데이트",
		BenchmarkDesc:  "이번 주 새로운 벤치마크 데이터",
	},
	LangDE: {
		DigestTitle:    "Wettbewerber-Überwachungsbericht",
		ChangesFound:   "%d Seitenänderungen erkannt",
		NoChanges:      "Keine Änderungen festgestellt",
		Severity:       "Schweregrad",
		Critical:       "Kritisch",
		Important:      "Wichtig",
		Minor:          "Geringfügig",
		ViewPage:       "Seite ansehen →",
		Unchanged:      "Unverändert",
		GeneratedBy:    "Automatisch erstellt von WatchBot",
		BenchmarkTitle: "📊 AI-Benchmark-Update",
		BenchmarkDesc:  "Neue Benchmark-Daten diese Woche",
	},
	LangES: {
		DigestTitle:    "Informe de Monitoreo de Competidores",
		ChangesFound:   "%d cambios de página detectados",
		NoChanges:      "Sin cambios detectados",
		Severity:       "Severidad",
		Critical:       "Crítico",
		Important:      "Importante",
		Minor:          "Menor",
		ViewPage:       "Ver Página →",
		Unchanged:      "Sin cambios",
		GeneratedBy:    "Generado automáticamente por WatchBot",
		BenchmarkTitle: "📊 Actualización de Benchmark AI",
		BenchmarkDesc:  "Nuevos datos de benchmark esta semana",
	},
}
