package i18n

// Labels holds all translatable UI text for email templates.
type Labels struct {
	DailyTitle  string
	Overview    string
	Important   string
	Watch       string
	Info        string
	ReadMore    string
	Source      string
	GeneratedBy string
	TokenUsage  string
}

// GetLabels returns the UI labels for a given language.
func GetLabels(lang Language) Labels {
	labels, ok := labelMap[lang]
	if !ok {
		return labelMap[LangZH] // fallback to Chinese
	}
	return labels
}

var labelMap = map[Language]Labels{
	LangZH: {
		DailyTitle:  "AI 热点日报",
		Overview:    "今日概览",
		Important:   "重要",
		Watch:       "关注",
		Info:        "了解",
		ReadMore:    "阅读原文 →",
		Source:      "来源",
		GeneratedBy: "由 DevKit NewsBot 自动生成",
		TokenUsage:  "Token: %d · 成本: $%.4f · Powered by MiniMax M2.5",
	},
	LangEN: {
		DailyTitle:  "AI Daily Digest",
		Overview:    "Today's Overview",
		Important:   "Important",
		Watch:       "Watch",
		Info:        "Info",
		ReadMore:    "Read More →",
		Source:      "Source",
		GeneratedBy: "Auto-generated by DevKit NewsBot",
		TokenUsage:  "Tokens: %d · Cost: $%.4f · Powered by MiniMax M2.5",
	},
	LangJA: {
		DailyTitle:  "AI デイリーダイジェスト",
		Overview:    "本日の概要",
		Important:   "重要",
		Watch:       "注目",
		Info:        "情報",
		ReadMore:    "続きを読む →",
		Source:      "ソース",
		GeneratedBy: "DevKit NewsBot により自動生成",
		TokenUsage:  "トークン: %d · コスト: $%.4f · Powered by MiniMax M2.5",
	},
	LangKO: {
		DailyTitle:  "AI 데일리 다이제스트",
		Overview:    "오늘의 개요",
		Important:   "중요",
		Watch:       "주목",
		Info:        "정보",
		ReadMore:    "자세히 보기 →",
		Source:      "출처",
		GeneratedBy: "DevKit NewsBot 자동 생성",
		TokenUsage:  "토큰: %d · 비용: $%.4f · Powered by MiniMax M2.5",
	},
	LangDE: {
		DailyTitle:  "AI Täglicher Überblick",
		Overview:    "Heutige Übersicht",
		Important:   "Wichtig",
		Watch:       "Beachten",
		Info:        "Info",
		ReadMore:    "Weiterlesen →",
		Source:      "Quelle",
		GeneratedBy: "Automatisch erstellt von DevKit NewsBot",
		TokenUsage:  "Token: %d · Kosten: $%.4f · Powered by MiniMax M2.5",
	},
	LangES: {
		DailyTitle:  "AI Resumen Diario",
		Overview:    "Resumen de Hoy",
		Important:   "Importante",
		Watch:       "Seguir",
		Info:        "Info",
		ReadMore:    "Leer más →",
		Source:      "Fuente",
		GeneratedBy: "Generado automáticamente por DevKit NewsBot",
		TokenUsage:  "Tokens: %d · Costo: $%.4f · Powered by MiniMax M2.5",
	},
}
